import { User, Task, Team, Employee, Attendance, Certification, EmployeeAnalytics, AIReview, Branch } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    role: 'admin',
    department: 'Human Resources',
    joinDate: '2022-01-15',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    id: 'user-2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    role: 'manager',
    department: 'Engineering',
    joinDate: '2021-06-20',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    id: 'user-3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    role: 'employee',
    department: 'Engineering',
    joinDate: '2023-03-10',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
  },
  {
    id: 'user-4',
    name: 'David Kim',
    email: 'david.kim@company.com',
    role: 'employee',
    department: 'Product',
    joinDate: '2023-01-08',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    id: 'user-5',
    name: 'Lisa Wang',
    email: 'lisa.wang@company.com',
    role: 'manager',
    department: 'Product',
    joinDate: '2021-09-05',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Implement new user authentication',
    description: 'Add OAuth2 support to the platform',
    status: 'in-progress',
    priority: 'high',
    assignee: mockUsers[1],
    assignedTo: mockUsers[2],
    dueDate: '2024-03-15',
    createdAt: '2024-02-20',
    tags: ['features'],
    startedAt: '2024-02-21',
  },
  {
    id: 'task-2',
    title: 'Design dashboard mockups',
    description: 'Create UI designs for the new dashboard',
    status: 'assigned',
    priority: 'high',
    assignee: mockUsers[1],
    assignedTo: mockUsers[3],
    dueDate: '2024-03-10',
    createdAt: '2024-02-18',
    tags: ['features'],
  },
  {
    id: 'task-3',
    title: 'Update documentation',
    description: 'Update API documentation with new endpoints',
    status: 'todo',
    priority: 'medium',
    assignee: mockUsers[1],
    dueDate: '2024-03-20',
    createdAt: '2024-02-21',
    tags: ['refactors'],
  },
  {
    id: 'task-4',
    title: 'Fix critical bug in payment module',
    description: 'Payment processing is failing for some users',
    status: 'review',
    priority: 'urgent',
    assignee: mockUsers[1],
    assignedTo: mockUsers[2],
    dueDate: '2024-03-01',
    createdAt: '2024-02-25',
    tags: ['bugs'],
    prLink: 'https://github.com/company/repo/pull/456',
    reviewer: mockUsers[1],
  },
  {
    id: 'task-5',
    title: 'Code review for PR #234',
    description: 'Review and approve pending pull request',
    status: 'qa',
    priority: 'medium',
    assignee: mockUsers[1],
    assignedTo: mockUsers[2],
    dueDate: '2024-03-05',
    createdAt: '2024-02-24',
    tags: ['bugs'],
    prLink: 'https://github.com/company/repo/pull/789',
    reviewer: mockUsers[1],
  },
  {
    id: 'task-6',
    title: 'Database optimization',
    description: 'Optimize slow queries in user service',
    status: 'completed',
    priority: 'high',
    assignee: mockUsers[1],
    assignedTo: mockUsers[2],
    dueDate: '2024-02-28',
    createdAt: '2024-02-10',
    tags: ['refactors'],
    completedAt: '2024-02-27',
  },
  {
    id: 'task-7',
    title: 'Implement caching strategy',
    description: 'Add Redis caching to improve performance',
    status: 'assigned',
    priority: 'high',
    assignee: mockUsers[1],
    assignedTo: mockUsers[3],
    dueDate: '2024-03-08',
    createdAt: '2024-02-22',
    tags: ['features'],
  },
  {
    id: 'task-8',
    title: 'Fix responsive design issues',
    description: 'Mobile layout not working correctly on tablets',
    status: 'review',
    priority: 'medium',
    assignee: mockUsers[1],
    assignedTo: mockUsers[2],
    dueDate: '2024-03-12',
    createdAt: '2024-02-23',
    tags: ['bugs'],
    prLink: 'https://github.com/company/repo/pull/567',
  },
];

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'Frontend Engineering',
    product: 'Web Platform',
    description: 'Building user interfaces and client applications',
    manager: mockUsers[1],
    members: [mockUsers[2], mockUsers[3], mockUsers[1]],
    memberCount: 3,
    createdAt: '2021-01-15',
  },
  {
    id: 'team-2',
    name: 'Backend Engineering',
    product: 'Core API',
    description: 'API development and server-side infrastructure',
    manager: mockUsers[1],
    members: [mockUsers[2], mockUsers[1]],
    memberCount: 2,
    createdAt: '2020-06-10',
  },
  {
    id: 'team-3',
    name: 'Product Team',
    product: 'Product Strategy',
    description: 'Product strategy and management',
    manager: mockUsers[4],
    members: [mockUsers[3], mockUsers[4]],
    memberCount: 2,
    createdAt: '2021-03-20',
  },
  {
    id: 'team-4',
    name: 'Design Team',
    product: 'Design System',
    description: 'UI/UX design and brand identity',
    manager: mockUsers[4],
    members: [mockUsers[4]],
    memberCount: 1,
    createdAt: '2020-12-01',
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    phone: '+1 (555) 123-4567',
    position: 'HR Manager',
    department: 'Human Resources',
    startDate: '2022-01-15',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    id: 'emp-2',
    name: 'Michael Chen',
    email: 'michael.chen@company.com',
    phone: '+1 (555) 234-5678',
    position: 'Engineering Manager',
    department: 'Engineering',
    startDate: '2021-06-20',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    id: 'emp-3',
    name: 'Emily Rodriguez',
    email: 'emily.rodriguez@company.com',
    phone: '+1 (555) 345-6789',
    position: 'Senior Frontend Developer',
    department: 'Engineering',
    manager: 'Michael Chen',
    startDate: '2023-03-10',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
  },
  {
    id: 'emp-4',
    name: 'David Kim',
    email: 'david.kim@company.com',
    phone: '+1 (555) 456-7890',
    position: 'Product Manager',
    department: 'Product',
    manager: 'Lisa Wang',
    startDate: '2023-01-08',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    id: 'emp-5',
    name: 'Lisa Wang',
    email: 'lisa.wang@company.com',
    phone: '+1 (555) 567-8901',
    position: 'Director of Product',
    department: 'Product',
    startDate: '2021-09-05',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
  },
  {
    id: 'emp-6',
    name: 'James Wilson',
    email: 'james.wilson@company.com',
    phone: '+1 (555) 678-9012',
    position: 'Backend Developer',
    department: 'Engineering',
    manager: 'Michael Chen',
    startDate: '2022-08-12',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
  },
];

export const mockAttendance: Attendance[] = Array.from({ length: 90 }, (_, i) => ({
  id: `attendance-${i}`,
  employeeId: mockEmployees[i % mockEmployees.length].id,
  date: new Date(Date.now() - (90 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  checkIn: `09:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}:00`,
  checkOut: `18:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}:00`,
  status: ['present', 'present', 'present', 'late', 'absent'][Math.floor(Math.random() * 5)] as any,
}));

export const mockCertifications: Certification[] = [
  {
    id: 'cert-1',
    employeeId: 'emp-3',
    name: 'AWS Certified Solutions Architect',
    issuer: 'Amazon Web Services',
    issueDate: '2023-06-15',
    expiryDate: '2025-06-15',
  },
  {
    id: 'cert-2',
    employeeId: 'emp-2',
    name: 'Certified Scrum Master',
    issuer: 'Scrum Alliance',
    issueDate: '2022-03-20',
    expiryDate: '2024-03-20',
  },
  {
    id: 'cert-3',
    employeeId: 'emp-4',
    name: 'Product Management Certification',
    issuer: 'Reforge',
    issueDate: '2023-12-01',
  },
  {
    id: 'cert-4',
    employeeId: 'emp-6',
    name: 'Google Cloud Professional Cloud Architect',
    issuer: 'Google Cloud',
    issueDate: '2023-09-10',
    expiryDate: '2025-09-10',
  },
  {
    id: 'cert-5',
    employeeId: 'emp-1',
    name: 'SHRM-CP Certification',
    issuer: 'Society for Human Resource Management',
    issueDate: '2021-08-12',
    expiryDate: '2024-08-12',
  },
];

export const mockAIReviews: AIReview[] = [
  {
    id: 'review-1',
    employeeId: 'emp-3',
    createdAt: '2024-02-25',
    description: 'Emily demonstrates excellent technical expertise and consistently delivers high-quality code. She is proactive in solving complex problems and mentors junior developers effectively.',
    score: 9.2,
    strengths: ['Technical Excellence', 'Problem Solving', 'Team Collaboration', 'Code Quality'],
    suggestions: ['Attend leadership training', 'Expand cross-functional collaboration', 'Document more best practices'],
  },
  {
    id: 'review-2',
    employeeId: 'emp-6',
    createdAt: '2024-02-24',
    description: 'James shows strong backend development skills with good understanding of system design. He should focus on improving documentation and cross-team communication.',
    score: 7.8,
    strengths: ['Backend Architecture', 'Problem Solving', 'Testing', 'Performance Optimization'],
    suggestions: ['Improve documentation habits', 'Attend communication workshops', 'Lead architecture reviews'],
  },
];

export const mockEmployeeAnalytics: EmployeeAnalytics[] = [
  {
    employeeId: 'emp-3',
    tasksCompleted: 12,
    attendanceRate: 98,
    kpiScore: 9.2,
    certifications: mockCertifications.filter(c => c.employeeId === 'emp-3'),
    strengths: ['Technical Excellence', 'Problem Solving', 'Team Collaboration'],
    areasForImprovement: ['Leadership', 'Cross-functional Projects'],
    overallScore: 9.0,
    review: mockAIReviews[0],
  },
  {
    employeeId: 'emp-6',
    tasksCompleted: 9,
    attendanceRate: 96,
    kpiScore: 7.8,
    certifications: mockCertifications.filter(c => c.employeeId === 'emp-6'),
    strengths: ['Backend Architecture', 'Problem Solving', 'Testing'],
    areasForImprovement: ['Documentation', 'Communication'],
    overallScore: 7.8,
    review: mockAIReviews[1],
  },
];

export const mockBranches: Branch[] = [
  {
    id: 'branch-1',
    name: 'Main Office - New York',
    address: '123 Business Ave, New York, NY 10001',
    latitude: 40.7128,
    longitude: -74.0060,
    radius: 500, // 500 meters
  },
  {
    id: 'branch-2',
    name: 'San Francisco Office',
    address: '456 Tech Street, San Francisco, CA 94105',
    latitude: 37.7749,
    longitude: -122.4194,
    radius: 400,
  },
  {
    id: 'branch-3',
    name: 'London Office',
    address: '789 Corporate Blvd, London, UK',
    latitude: 51.5074,
    longitude: -0.1278,
    radius: 400,
  },
];
